### ISSUE TITLE
Collapse boxes don't open on initial load (Indonesian only)

### ISSUE THREAD

**Issue by ninaszymor** [raspberrypilearning/ghostbusters#135]
On initial load, collapse boxes don't open but navigating to the next/previous step and then going back resolves the problem. 

Happens in Indonesian (id-ID) only.

@Jonic

**Comment by gregorywood** [comment]
This sounds like a front-end bug, not design, so don't think it's for me 👍

**Comment by martinohanlon** [comment]
Sigh sorry @gregorywood wrong Greg. @gr-eg - what do you think?

**Comment by gr-eg** [comment]
Yep, this should be in `projects-ui`. I'll transfer it

**Comment by gr-eg** [comment]
Moved to `projects-ui` https://github.com/RaspberryPiFoundation/projects-ui/issues/1368
