### ISSUE TITLE
ghost sprite images

### ISSUE THREAD

**Issue by JaninaPi** [raspberrypilearning/ghostbusters#143]
There are seemingly random images of the ghost sprite in steps 3, 7, and 8. Are they there on purpose?

(I am trying really hard to come up with a clever 'ghost in the machine' joke.)

**Comment by martinohanlon** [comment]
The sprites are there to show which sprite to add the code too.

I've noticed that a couple of broken.

**Comment by martinohanlon** [comment]
Im not sure we need both though on this hint though. 1 would do 
![image](https://user-images.githubusercontent.com/2329501/48631831-59391400-e9b7-11e8-946c-fd81693a74d4.png)

**Comment by JaninaPi** [comment]
Aha! I will take that second one out of step 3 then

**Comment by JaninaPi** [comment]
In fact, I will leave it alone :D

**Comment by martinohanlon** [comment]
Done

**Comment by JaninaPi** [comment]
🎊
